export const VISION_TIMER_DURATION = 30;
export const VISION_TIMER_REST_DURATION = 10;
export const VISION_TIMER_REPEAT_ALARM_INTERVAL = 3000;
export const VISION_TIMER_REPEAT_INTERVAL_STOP_AFTER = 30000;
