export const VISION_TIMER_DURATION = 20 * 60;
export const VISION_TIMER_REST_DURATION = 20;
export const VISION_TIMER_REPEAT_ALARM_INTERVAL = 3000;
export const VISION_TIMER_REPEAT_INTERVAL_STOP_AFTER = 30000;
export const POMODORO_FOCUS_DURATION = 25 * 60;
export const POMODORO_SHORT_BREAK_DURATION = 5 * 60;
export const POMODORO_LONG_BREAK_DURATION = 30 * 60;


// prod config
// export const VISION_TIMER_DURATION = 20 * 60;
// export const VISION_TIMER_REST_DURATION = 20;
// export const VISION_TIMER_REPEAT_ALARM_INTERVAL = 3000;
// export const VISION_TIMER_REPEAT_INTERVAL_STOP_AFTER = 30000;
// export const POMODORO_FOCUS_DURATION = 25 * 60;
// export const POMODORO_SHORT_BREAK_DURATION = 5 * 60;
// export const POMODORO_LONG_BREAK_DURATION = 30 * 60;

