export const VISION_TIMER_DURATION = 20 * 60;
export const VISION_TIMER_REST_DURATION = 20;
export const VISION_TIMER_REPEAT_ALARM_INTERVAL = 3000;
export const VISION_TIMER_REPEAT_INTERVAL_STOP_AFTER = 30000;
export const POMODORO_FOCUS_DURATION = 25 * 60;
export const POMODORO_SHORT_BREAK_DURATION = 5 * 60;
export const POMODORO_LONG_BREAK_DURATION = 30 * 60;
export const BREATHING_BREATHS_AMOUNT = 3;
export const BREATHING_BREATH_DURATION = 1.82;
export const BREATHING_HOLD_BREATH_SMALL_DURATION = 1.5;


// prod config
// export const VISION_TIMER_DURATION = 20 * 60;
// export const VISION_TIMER_REST_DURATION = 20;
// export const VISION_TIMER_REPEAT_ALARM_INTERVAL = 3000;
// export const VISION_TIMER_REPEAT_INTERVAL_STOP_AFTER = 30000;
// export const POMODORO_FOCUS_DURATION = 25 * 60;
// export const POMODORO_SHORT_BREAK_DURATION = 5 * 60;
// export const POMODORO_LONG_BREAK_DURATION = 30 * 60;

